name: 'Sparse checkout action'
description: 'Sparse checkout a git repository'
branding:
  icon: 'minimize-2'
  color: 'gray-dark'
inputs:
  # Sparse checkout
  patterns:
    description: >
      Write a set of patterns to the sparse-checkout file.

      [Learn more about set](https://git-scm.com/docs/git-sparse-checkout#Documentation/git-sparse-checkout.txt-emsetem)
    required: true

  # Same as actions/checkout
  repository:
    description: 'Repository name with owner. For example, snow-actions/sparse-checkout'
    default: ${{ github.repository }}
    required: false
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
    required: false
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - name: Setting git path
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          echo "GIT=/usr/local/bin/git" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "GIT=/cmd/git" >> $GITHUB_ENV
        else
          echo "GIT=/usr/bin/git" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Getting Git version info
      run: |
        echo "::group::Getting Git version info"
        $GIT version
        echo "::endgroup::"
      shell: bash

    - name: cleanup #https://github.com/actions/checkout/issues/211
      run: |
        sudo chown -R runner:runner ${{ github.workspace }}
      shell: bash

    - name: Ensure clean directory
      run: |
        pwd
        ls -la $DIRECTORY || true
        sudo rm -rf $DIRECTORY || true
      env:
        DIRECTORY: ${{ inputs.path }}
      shell: bash

    - name: Disabling automatic garbage collection
      run: |
        echo "::group::Disabling automatic garbage collection"
        $GIT config --local gc.auto 0
        echo "::endgroup::"
      working-directory: ${{ inputs.path }}
      shell: bash
      
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Clone the repository (bare)
      run: |
        echo "::group::Cloning the repository"
        $GIT -c protocol.version=2 clone --branch ${{ steps.extract_branch.outputs.branch }} --filter=blob:none --no-checkout ${GITHUB_SERVER_URL/https:\/\//https:\/\/x-access-token:${TOKEN}@}/${REPOSITORY} .
        echo "::endgroup::"
      env:
        REPOSITORY: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
      working-directory: ${{ inputs.path }}
      shell: bash

    - name: Sparse checkout
      run: |
        echo "::group::Setting up sparse checkout"
        $GIT sparse-checkout set $PATTERNS
        $GIT read-tree -mu HEAD
        echo "::endgroup::"
      env:
        PATTERNS: ${{ inputs.patterns }}
      working-directory: ${{ inputs.path }}
      shell: bash
